import {readFileSync,writeFileSync,existsSync,renameSync} from 'node:fs';
import {join} from 'node:path';
import {configPath,readStudio,layoutOf,listExperiences} from './studio.mjs';
import {wranglerConfig} from './scaffold.mjs';
import {paidReleases} from './parts-upload.mjs';
const parse=t=>JSON.parse(t.replace(/^\s*\/\/.*$/gm,''));
const read=file=>existsSync(file)?parse(readFileSync(file,'utf8')):{};
function merge(base,custom) {
  if(Array.isArray(custom))return custom;
  if(custom && typeof custom==='object')return Object.fromEntries([...new Set([...Object.keys(base??{}),...Object.keys(custom)])].sort().map(k=>[k,k in custom?merge(base?.[k],custom[k]):base[k]]));
  return custom;
}
/** Generated output is never an input. Studio additions belong in wrangler.custom.json. */
export function updateWorkerConfig(root,generated) {
  const file=configPath(root),next=merge(parse(generated),read(join(root,'wrangler.custom.json')));
  const text='// Generated by homie-studio. Edit studio.json or wrangler.custom.json, then build.\n'+JSON.stringify(next,null,2)+'\n';
  if(!existsSync(file)||readFileSync(file,'utf8')!==text) {const temp=`${file}.${process.pid}.tmp`;writeFileSync(temp,text);renameSync(temp,file);}
}
export function refreshWorkerConfig(root,overrides={}) {
  const studio=readStudio(root),cf=studio.cloudflare;
  if(!cf?.worker)return;
  const metadata=read(join(root,'site/src/functions/declarations.json'));
  const functions=Array.isArray(metadata)?metadata:[];
  const tools=read(join(root,'site/src/tools/declarations.json'));
  const ai=cf.ai??listExperiences(root).some(g=>g.decide===true || g.chat!==false && (g.chat?.mode??'text')==='text' && g.chat?.ai!==false);
  const paid=paidReleases(root).length>0||existsSync(join(root,'shop.json'))||tools.paid===true;
  updateWorkerConfig(root,wranglerConfig({worker:cf.worker,name:studio.name,d1:cf.d1,d1Id:cf.d1Id,r2:cf.r2,layout:layoutOf(root),ai,paidParts:paid,partsRateLimit:cf.purchaseRateLimit??null,routes:cf.routes??null,triggers:functions.length?{crons:[...new Set(['* * * * *',...functions.map(f=>f.schedule).filter(Boolean)])].sort()}:null,...overrides}));
}
