import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,readFileSync,readdirSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {esbuildOf,PKG,loadGame,writeGame} from './rules-kit.mjs';
const scratch=mkdtempSync(join(tmpdir(),'rules-compat-'));test.after(()=>rmSync(scratch,{recursive:true,force:true}));
test('0.45.0 default solid terrain casts retain seeded results and charged cost',async()=>{
 const esbuild=await esbuildOf(),out=join(scratch,'cast.mjs');await esbuild.build({stdin:{contents:`export {castMap3 as current} from './rules/collision.ts';export {castMap3 as old} from './test/fixtures/compat-0450/collision.ts';export {prepareTile} from './test/fixtures/compat-0450/terrain.ts';export {compileMap} from './rules/rules.ts';export {G} from './rules/guard.ts';`,resolveDir:PKG},bundle:true,platform:'node',format:'esm',outfile:out});const L=await import(out);
 const maps=[['stormbreak',JSON.parse(readFileSync(join(PKG,'test/fixtures/stormbreak-terrain/map.json')))]];for(const dir of readdirSync(join(PKG,'starters'))){const p=join(PKG,'starters',dir,'map/main.json');if(existsSync(p)){const raw=JSON.parse(readFileSync(p));if(raw.bounds?.min?.length===3)maps.push([dir,raw]);}}
 maps.push(['solid-slopes',{bounds:{min:[-50,-50,-5],max:[50,50,30]},heightTiles:[{at:[-10,-10,0],size:[20,20],heights:[0,4,2,6],base:-1},{at:[-5,-5,7],size:[10,10],heights:[0,1,1,0],base:-1}],boxes:[{min:[15,15,0],max:[19,19,5]}]}]);
 let seed=4520,casts=0;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);for(const [name,raw] of maps){const map=L.compileMap(raw);for(const t of map.heightTiles??[])L.prepareTile(t);for(let i=0;i<512;i++){const p={x:random()*60-30,y:random()*60-30,z:random()*12},d={x:random()*12-6,y:random()*12-6,z:random()*12-6},shape={shape:i%3?'capsule':'sphere',radius:i%4?.42:0,height:i%3?1.8:0};L.G.left=1e8;const old=L.old(map,p,d,shape),cost=1e8-L.G.left;L.G.left=1e8;const current=L.current(map,p,d,shape);assert.deepEqual(current,old,`${name}:${i}`);assert.equal(1e8-L.G.left,cost,`${name}:${i} cost`);casts++;}}L.G.left=Infinity;console.log(JSON.stringify({seed:4520,maps:maps.map(([n])=>n),casts,drift:0,costDrift:0}));
});
test('new capability names remain legal plain fields and destructured local values',async()=>{
 const rules=`import {defineRules,f} from '@homie-rocks/studio/rules';function total({label,dispatch,rayAll,rays,restart}){return label+dispatch+rayAll+rays+restart;}export default defineRules({contract:2,space:{dims:2},entities:{thing:{fields:{value:f.u8()},tick(w,s){const data={label:1,dispatch:2,rayAll:3,rays:4,restart:5};const {label,dispatch,rayAll,rays,restart}=data;s.value=total(data)+label+dispatch+rayAll+rays+restart;}}},room:{start(w){w.spawn('thing',{x:0,y:0});}}});`;
 const L=await loadGame(scratch,writeGame(scratch,'names',{rules}),'names'),c=L.R.compileRules(L.def,{map:L.R.compileMap({bounds:{min:[-10,-10],max:[10,10]}}),seats:2}),core=L.C.createCore(c,{seed:4520});for(let i=0;i<3;i++)core.step();assert.equal(core.stats.errors,0,core.stats.lastError);assert.equal(core.snapshot()[1][0][7][0],30);
});
test('three-argument rays keep inside-solid misses; options explicitly enable inside hits',async()=>{
 const rules=`import {defineRules,f} from '@homie-rocks/studio/rules';export default defineRules({contract:2,space:{dims:3},entities:{marker:{fields:{}}},shared:{old:f.fix(),enhanced:f.fix()},room:{start(w){const p={x:0,y:0,z:1},d={x:1,y:0,z:0};w.shared.old=w.ray(p,d,10)?.dist??-1;w.shared.enhanced=w.ray(p,d,10,{geometryOnly:true})?.dist??-1;}}});`;
 const L=await loadGame(scratch,writeGame(scratch,'inside',{rules}),'inside'),c=L.R.compileRules(L.def,{map:L.R.compileMap({bounds:{min:[-20,-20,0],max:[20,20,20]},boxes:[{min:[-1,-1,0],max:[1,1,3]}]}),seats:2}),core=L.C.createCore(c,{seed:4520});core.step();assert.equal(core.stats.errors,0,core.stats.lastError);assert.deepEqual(L.P.unpackFields(c.shared,core.save().shared,3),{old:-1,enhanced:0});
});
test('seeded baked routes cross more than 64 nodes and respect live obstacles without partial paths',async()=>{
 const esbuild=await esbuildOf(),out=join(scratch,'route.mjs');await esbuild.build({stdin:{contents:`export {routeGraph} from './rules/navigation.ts';export {G} from './rules/guard.ts';`,resolveDir:PKG},bundle:true,platform:'node',format:'esm',outfile:out});const {routeGraph,G}=await import(out);
 const graph=Object.freeze(Array.from({length:160},(_,i)=>Object.freeze([i,0,0,Object.freeze([...(i?[i-1]:[]),...(i<159?[i+1]:[])])])));G.left=125000;const path=routeGraph(graph,0,159,[],.4,1.8);assert.deepEqual(path,Array.from({length:160},(_,i)=>i));assert(G.left>100000);G.left=125000;assert.deepEqual(routeGraph(graph,0,159,[{min:{x:79.5,y:-2,z:0},max:{x:80.5,y:2,z:3},r:0}],.4,1.8),[]);G.left=Infinity;
});
test('scratch sweeps may skip redundant ground checks without changing default grounding',async()=>{
 const esbuild=await esbuildOf(),out=join(scratch,'sweep.mjs');await esbuild.build({stdin:{contents:`export {sweepMap} from './rules/math.ts';export {compileMap} from './rules/rules.ts';export {G} from './rules/guard.ts';`,resolveDir:PKG},bundle:true,platform:'node',format:'esm',outfile:out});const {sweepMap,compileMap,G}=await import(out),map=compileMap({bounds:{min:[-10,-10,0],max:[10,10,10]}}),shape={shape:'capsule',radius:.4,height:1.8};
 const ordinary={pos:{x:0,y:0,z:2},grounded:true},explicit={pos:{x:0,y:0,z:2},grounded:true};G.left=125000;sweepMap(map,ordinary,{x:1,y:0,z:0},.4,3,shape);const normalCost=125000-G.left;G.left=125000;sweepMap(map,explicit,{x:1,y:0,z:0},.4,3,shape,{ground:false});assert.deepEqual(explicit.pos,ordinary.pos);assert.equal(ordinary.grounded,false);assert.equal(explicit.grounded,true);assert(125000-G.left<normalCost);G.left=Infinity;
});
test('collider projection includes only declared fields and unchanged geometry is absent from deltas',async()=>{
 const rules=`import {defineRules,f} from '@homie-rocks/studio/rules';export default defineRules({contract:2,space:{dims:3},entities:{wall:{body:{shape:'box',radius:1,height:2,maxSpeed:0},collider:{fields:['color']},fields:{color:f.u8({init:7}),secret:f.u32({visibility:'server'}),hp:f.u16({init:100})},tick(w,s){s.secret++;if(w.tick===4)w.place(s,{x:2,y:0,z:0});}}},room:{start(w){w.spawn('wall',{x:0,y:0,z:0});}}});`;
 const L=await loadGame(scratch,writeGame(scratch,'collider-fields',{rules}),'collider-fields'),c=L.R.compileRules(L.def,{map:L.R.compileMap({bounds:{min:[-10,-10,0],max:[10,10,10]}}),seats:2}),core=L.C.createCore(c,{seed:4520});core.step();const a=core.snapshot();assert.deepEqual(a[2][2][0][8].fields,{color:7});core.step();const b=core.snapshot();assert.deepEqual(b[2],a[2]);const {snapshotEncoder,snapshotDecoder}=await import('../rules/interest.mjs'),enc=snapshotEncoder(20),dec=snapshotDecoder(),first=enc.encode({e:1,k:1,d:a});dec.decode(first);const delta=enc.encode({e:1,k:2,d:b});assert(!Object.hasOwn(delta.d,'collision'));assert.deepEqual(dec.decode(delta).d[2],a[2]);
 const restored=L.C.createCore(c,{restore:core.save()});restored.step();restored.step();const changed=restored.snapshot();assert.notEqual(changed[2][0],b[2][0]);assert.equal(changed[2][0],4);assert.equal(changed[2][2][0][2],2);
});
test('bidirectional baked routes match seeded directed Dijkstra costs',async()=>{
 const esbuild=await esbuildOf(),out=join(scratch,'route-cost.mjs');await esbuild.build({stdin:{contents:`export {routeGraph} from './rules/navigation.ts';export {G} from './rules/guard.ts';`,resolveDir:PKG},bundle:true,platform:'node',format:'esm',outfile:out});const {routeGraph,G}=await import(out);let seed=4520;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296),edge=(a,b)=>Math.hypot(b[0]-a[0],b[1]-a[1])+Math.max(0,b[2]-a[2])*.3;
 for(let trial=0;trial<80;trial++){const graph=Array.from({length:40},()=>[random()*20,random()*20,random()*4,[]]);for(let i=0;i<40;i++)for(let n=0;n<4;n++){const j=Math.floor(random()*40);if(j!==i&&!graph[i][3].includes(j))graph[i][3].push(j);}const costs=Array(40).fill(Infinity),done=new Set();costs[0]=0;for(let n=0;n<40;n++){let at=-1;for(let i=0;i<40;i++)if(!done.has(i)&&(at<0||costs[i]<costs[at]))at=i;if(at<0||!Number.isFinite(costs[at]))break;done.add(at);for(const next of graph[at][3])costs[next]=Math.min(costs[next],costs[at]+edge(graph[at],graph[next]));}G.left=125000;const route=routeGraph(graph,0,39,[],.4,1.8);if(!Number.isFinite(costs[39]))assert.deepEqual(route,[]);else{assert.equal(route[0],0);assert.equal(route.at(-1),39);let cost=0;for(let i=1;i<route.length;i++){assert(graph[route[i-1]][3].includes(route[i]));cost+=edge(graph[route[i-1]],graph[route[i]]);}assert(Math.abs(cost-costs[39])<1e-9,`trial ${trial}`);}assert(G.left>0);}G.left=Infinity;
});
test('declared graphs validate at compilation and seeded restored searches keep their route and cost',async()=>{
 const graph=Array.from({length:2048},(_,i)=>[i,0,0,[...(i?[i-1]:[]),...(i<2047?[i+1]:[])]]);
 const rules=`import {defineRules,f} from '@homie-rocks/studio/rules';const graph=${JSON.stringify(graph)};export default defineRules({contract:2,space:{dims:3},navigation:{walk:graph},entities:{walker:{fields:{count:f.u16()},tick(w,s){s.count=w.route('walk',0,20,{radius:.4,height:1.8}).length;}}},room:{start(w){w.spawn('walker',{x:0,y:0,z:0});}}});`;
 const L=await loadGame(scratch,writeGame(scratch,'declared-routes',{rules}),'declared-routes'),env={map:L.R.compileMap({bounds:{min:[-10,-10,0],max:[2100,10,10]}}),seats:2},compiled=L.R.compileRules(L.def,env),core=L.C.createCore(compiled,{seed:4520});
 core.step();const restored=L.C.createCore(compiled,{restore:core.save()});for(let i=0;i<20;i++){core.step();restored.step();assert.deepEqual(restored.save(),core.save());assert.equal(core.stats.errors,0,core.stats.lastError);assert.equal(restored.stats.errors,0,restored.stats.lastError);}assert.equal(L.P.unpackFields(compiled.kinds[0].fields,core.save().ents[0][17],3).count,21);assert(core.stats.maxUnits<10000,JSON.stringify(core.stats));
 const bad=structuredClone(graph);bad[0][3]=[9999];assert.throws(()=>L.R.compileRules(L.R.defineRules({...L.def,navigation:{bad}}),env),/links/);
 assert.throws(()=>L.R.compileRules(L.R.defineRules({...L.def,navigation:{a:graph,b:graph,c:graph,d:graph,e:graph}}),env),/8192/);
});
