import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {appendServerRecord,getSave,writeSaves,wipeSaves,wipeStatements} from '../worker/saves.mjs';import {PLAYERS_MIGRATION} from '../worker/players.mjs';import {studioFiles} from '../lib/scaffold.mjs';import {loadGame,writeGame,hostRig} from './rules-kit.mjs';
const scratch=mkdtempSync(join(tmpdir(),'rules-records-'));test.after(()=>rmSync(scratch,{recursive:true,force:true}));
function database(){const sql=new DatabaseSync(':memory:');sql.exec(studioFiles({name:'Records',slug:'records'})['site/migrations/0001_studio.sql']);sql.exec(PLAYERS_MIGRATION);const stmt=(q,a=[])=>({bind:(...v)=>stmt(q,v),first:async()=>sql.prepare(q).get(...a)??null,all:async()=>({results:sql.prepare(q).all(...a)}),run:async()=>({meta:{changes:Number(sql.prepare(q).run(...a).changes)}})});return {sql,env:{DB:{prepare:q=>stmt(q),batch:async list=>Promise.all(list.map(s=>s.run()))}}};}
test('server receipts deduplicate, survive browser writes and both reset paths, retain newest 100',async()=>{const {sql,env}=database();try{sql.prepare("INSERT INTO players(id,name,named,guest,owner,created_at,seen_at) VALUES('p','Player',0,1,0,1,1)").run();const receipt={id:'round-1',endedAt:1,place:1,won:true,kills:2,damage:300};await appendServerRecord(env,'p','game','server:career',receipt);await appendServerRecord(env,'p','game','server:career',{...receipt,kills:999});assert.equal((await getSave(env,'p','game','server:career')).value.matches[0].kills,2);
 const forged=await writeSaves(env,'p','game',{set:[{key:'server:career',value:{matches:[]},base:1}]});assert.equal(forged.results[0].error,'authority');await wipeSaves(env,'p','game');await wipeStatements(env,'p','game').all();assert.equal((await getSave(env,'p','game','server:career')).value.matches.length,1);
 for(let i=2;i<=105;i++)await appendServerRecord(env,'p','game','server:career',{...receipt,id:'round-'+i,endedAt:i});const saved=(await getSave(env,'p','game','server:career')).value;assert.equal(saved.matches.length,100);assert.equal(saved.matches[0].id,'round-105');assert.equal(saved.matches.at(-1).id,'round-6');}finally{sql.close();}});
test('seeded host writes authority totals for eligible humans over three completed rounds',async()=>{const rules=`import {defineRules,defineMove,f} from '@homie-rocks/studio/rules';export default defineRules({contract:2,space:{dims:2},move:defineMove({runner(){}}),shared:{match:f.text(40)},entities:{runner:{player:true,body:{shape:'circle',radius:.4,maxSpeed:0},fields:{ready:f.bit({init:true}),kills:f.u16(),score:f.u16({score:true})},tick(w,s){s.kills++;s.score=s.kills;}}},room:{records:{key:'server:career',identity:'match',eligible:'ready',fields:{kills:'kills'}},rounds:{seconds:1,breakSeconds:1},bots:{keep:2},join(c,p){return{kind:'runner',at:{x:p.seat,y:0}};},on:{roundStart(w){w.shared.match='seed-4520:'+w.round.n;}}}});`;const L=await loadGame(scratch,writeGame(scratch,'records',{rules}),'records'),c=L.R.compileRules(L.def,{map:L.R.compileMap({bounds:{min:[-10,-10],max:[10,10]}}),seats:2}),written=[],r=hostRig(L,c,{host:{record:(owner,key,value)=>written.push({owner,key,value})}});r.join(0);r.ticks(122);assert.equal(written.length,3);assert(written.every(r=>r.owner==='p1'&&r.key==='server:career'&&r.value.kills>0));assert.equal(new Set(written.map(r=>r.value.id)).size,3);r.host.stop();});
test('record-enabled play authenticates a new guest before issuing the room page',async()=>{
 const {default:worker}=await import('../worker/index.mjs');const {sql,env}=database();env.STUDIO_NAME='Records';const cat={studio:{name:'Records',slug:'records',theme:{}},games:[{id:'records',name:'Records',players:{min:1,max:8},room:{records:true},landing:{hero:{},credits:{people:[]}}}],songs:[],videos:[],posts:[],site:{pages:[],partials:{}}};env.ASSETS={fetch:async req=>new URL(req.url).pathname==='/games.json'?Response.json(cat):new Response('missing',{status:404})};
 try{const request=new Request('https://records.example/records/play?room=proof',{headers:{'user-agent':'Mozilla/5.0','cf-connecting-ip':'198.51.100.42'}}),response=await worker.fetch(request,env,{waitUntil(){}});assert.equal(response.status,200,await response.clone().text());assert(response.headers.get('set-cookie'));assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM players').get().n,1);const player=sql.prepare('SELECT id FROM players').get().id;await appendServerRecord(env,player,'records','server:career',{id:'proof-round',endedAt:1,kills:2});const cookie=response.headers.getSetCookie().map(c=>c.split(';')[0]).join('; '),read=await worker.fetch(new Request('https://records.example/api/player/saves/records/server%3Acareer',{headers:{cookie}}),env,{waitUntil(){}});assert.equal(read.status,200);assert.equal((await read.json()).value.matches[0].kills,2);}finally{sql.close();}
});
